version: '3.8'
services:
  database:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
    driver: local
